CREATE OR REPLACE VIEW VW_USERS_STATUS AS
    SELECT * FROM USERS_STATUS;

CREATE OR REPLACE VIEW VW_USERS AS
    SELECT USER_ID, USERNAME, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, USERS.STATUS_ID, USERS_STATUS.NAME STATUS_NAME, ADMIN FROM USERS
        JOIN USERS_STATUS ON USERS.STATUS_ID = USERS_STATUS.STATUS_ID;